### ISSUE TITLE
Circlefade

### ISSUE THREAD

**Issue by max-circlefade** [VCVRack/library#559]
Hey everyone, 
I've started developing VCV plugins and I'd love them to be added to the plugin manager!

Name: Circlefade
Version: 0.6.2
Source: https://github.com/max-circlefade/Circlefade
Last commit: 8cf230a2575c92a8a07d303526a5a8adac6f5042

Many thanks :)

```
{
  "name": "Circlefade",
  "author": "Max Circlefade",
  "license": "CC0 1.0 Universal",
  "mail": "max@circlefade.com",
  "pluginUrl": "https://github.com/max-circlefade/Circlefade",
  "authorUrl": "https://github.com/max-circlefade",
  "manualUrl": "https://github.com/max-circlefade/Circlefade/blob/master/README.md",
  "latestVersion": "0.6.2"
  "donate": "https://www.paypal.me/circlefade"
}
```

Hope everything is fine!

**Comment by cschol** [comment]
Thank you for submitting your plugin. It has been reviewed and integrated in the `library` repository. The next time Andrew updates the builds it will be made available via the Plugin Manager for all supported platforms. Please let us know in **this** issue when a new version of the plugin is available. We will reopen it.

Also, since the Rack `v1` API is stable now, please also consider porting your plugin to Rack version 1.0.0, which is targeted to be released next month. See the [migration guide](https://vcvrack.com/manual/Migrate1.html) for more information on how to migrate your plugin. Once the migrated version is done, you can let us know in **this** issue and we will integrate the new version into the library repository.

**Comment by max-circlefade** [comment]
Hey everyone! 
Super happy to share my new commit, updating to the 1.0 requirements and bringing some new modules :)
Had a blast playing around the new Rack, congrats!!
The commit is 
2fb0757fbdb7da3aa90f32322ec969e0ef324579
from https://github.com/max-circlefade/Circlefade

Many thanks and best regards,
Max

**Comment by cschol** [comment]
Invalid URLs in `plugin.json`: https://github.com/max-circlefade/Circlefade/issues/3

**Comment by max-circlefade** [comment]
Woops sorry here is the corrected commit: 238e2e4e03fbe58a1d8ae659947b5fd36fd9a517
Thanks :)

**Comment by max-circlefade** [comment]
Hey everyone!
Fresh commit with a new Random module, that has a Clk Input, and some looping / scales options :)
-> 38075bed27f8496820527200f43bfc7f908efed9
https://github.com/max-circlefade/Circlefade

Many thanks!
Best regards, Max

**Comment by flyingLowSounds** [comment]
Attn: @AndrewBelt , @cschol 

There doesn't seem to be any activity from max-circlefade for over a year. 

I have reached out to them via this [gh issue](https://github.com/max-circlefade/Circlefade/issues/6). If they reply and resume maintenace and porting to v2, all is fine. 

If not, I am putting myself forward to be the maintainer going forward. 

I reference [this comment by Vortico](https://community.vcvrack.com/t/circlefade-website-manuals-spammy-links/13516/6?u=flyinglow).

This is [my repo](https://github.com/flyingLowSounds/Circlefade).

flyingLow

**Comment by MaximePHAMTHANH** [comment]
Hey! Unfortunately we've gone banckrupt 1 year and a half ago, and I've moved on to other projects.
You can absolutely take full controll of the VCV modules, feel free to rename them under a new brand name
Also, I've seen this https://community.vcvrack.com/t/circlefade-website-manuals-spammy-links/13516, saying our domain name has been used for fraudulous reasons.
Obviously I have no responsability in this as I'm not the owner of this domain far quite some time now.

**Comment by AndrewBelt** [comment]
Sorry to hear that! After the brand is changed, are you okay with keeping the `Circlefade` plugin slug, which would maintain patch compatibility, VCV account subscriptions, and links to https://library.vcvrack.com/Circlefade? If not, patch compatibility could be maintained by a hard-coded list of slug migrations in Rack itself.

**Comment by MaximePHAMTHANH** [comment]
I think the best solution would be to keep the slug so compatibility is maintained.
But if it's easier to change it, it's completely fine
I just don't want my old website to be referenced anymore and mislead people into scamy stuff

**Comment by AndrewBelt** [comment]
@MaximePHAMTHANH Okay and just to verify: for the *brand* name, would you prefer the fork to change the "Circlefade" brand name or keep it?

**Comment by MaximePHAMTHANH** [comment]
You can keep it yeah I guess it makes more sence since the brand is also on the modules graphics (I don't have acces to the circlefade github account anymore since my email has been cancelled)
Anyways thanks for everything Andrew I had a lot of fun with VCV back in the days and I hope it keeps beeing this amazing project :)
